D2S equ 10h
E2  equ 11h
F2  equ 12h 
F2S equ 13h 
G2  equ 14h 
G2S equ 15h 
A2  equ 16h 
A2S equ 17h 
B2  equ 18h 

C3  equ 19h 
C3S equ 1ah 
D3  equ 1bh 
D3S equ 1ch 
E3  equ 1dh 
F3  equ 1eh 
F3S equ 1fh 
G3  equ 20h 
G3S equ 21h 
A3  equ 22h 
A3S equ 23h 
B3  equ 24h 

C4  equ 25h
C4S equ 26h 
D4  equ 27h
D4S equ 28h
E4  equ 29h
F4  equ 2ah
F4S equ 2bh
G4  equ 2ch
G4S equ 2dh 
A4  equ 2eh
A4S equ 2fh
B4  equ 30h

C5  equ 31h 
C5S equ 32h
D5  equ 33h 
D5S equ 34h 
E5  equ 35h
F5  equ 36h 
F5S equ 37h
G5  equ 38h 
G5S equ 39h
A5  equ 3ah
A5S equ 3bh 
B5  equ 3ch

C6  equ 3dh 
C6S equ 3eh
D6  equ 3fh 
D6S equ 40h
E6  equ 41h
F6  equ 42h 
F6S equ 43h
G6  equ 44h 
G6S equ 45h
A6  equ 46h 
A6S equ 47h
B6  equ 48h

C7  equ 49h  
C7S equ 4ah 
D7  equ 4bh
D7S equ 4ch
E7  equ 4dh 
F7  equ 4eh
F7S equ 4fh
G7  equ 50h 
G7S equ 51h
A7  equ 52h 
A7S equ 53h
B7  equ 54h 

C8  equ 55h 

PAUSE equ 80h
